PolymeshAssociation/polymesh-rest-api

.github/CODEOWNERS
.github/workflows/main.yml
src/notifications/notifications.service.ts
src/subscriptions/subscriptions.service.ts
src/transactions/transactions.service.ts

[DA-409](https://polymesh.atlassian.net/browse/DA-409)
Updated the CODEOWNERS list to remove Jere and add myself and Eric

chore: 🤖 Update CODEOWNERS

---

package.json
yarn.lock

Include vault signing manager fix for large payloads

fix: 🐛 fix vault signing erroring on large payloads

---

src/accounts/accounts.controller.spec.ts
src/accounts/accounts.controller.ts
src/accounts/accounts.service.spec.ts
src/accounts/accounts.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

✅ Closes: DA-48
https://polymesh.atlassian.net/browse/DA-48
- adds POST /accounts/freeze-secondary-accounts
- adds POST /accounts/unfreeze-secondary-accounts

feat: 🎸 freeze/unfreeze secondary accounts

---

package.json
src/accounts/accounts.controller.spec.ts
src/accounts/accounts.controller.ts
src/accounts/accounts.service.spec.ts
src/accounts/accounts.service.ts
src/accounts/dto/modify-permissions.dto.ts
src/accounts/dto/permissioned-account.dto.ts
src/accounts/dto/revoke-permissions.dto.ts
src/identities/dto/permissions-like.dto.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts
yarn.lock

DA-47
Add endpoints to modify and revoke account permissions

feat: 🎸 Add endpoints to modify/revoke account permissions

---

.github/workflows/main.yml
.vscode/settings.json
README.md
package.json
release.config.js
yarn.lock

[DA-438](https://polymesh.atlassian.net/browse/DA-438)
automatically publish docker images

chore: 🤖 add semantic release bot with docker extension

---

release.config.js

Remove copy pasta from the docker plugin comment

docs: ✏️ update comment in release.config

---

src/accounts/accounts.controller.spec.ts
src/accounts/accounts.controller.ts
src/accounts/accounts.module.ts
src/accounts/accounts.util.spec.ts
src/network/network.controller.spec.ts
src/network/network.service.spec.ts
src/network/network.service.ts
src/portfolios/porfolios.controller.spec.ts
src/test-utils/consts.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-64
adds `GET /accounts/treasury` method to retrieve treasury account information

feat: 🎸 get treasury account

---

src/compliance/compliance-requirements.controller.spec.ts
src/compliance/compliance-requirements.controller.ts
src/compliance/compliance-requirements.service.spec.ts
src/compliance/compliance-requirements.service.ts
src/compliance/mocks/compliance-requirements.mock.ts
src/compliance/models/compliance-status.model.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-64
adds endpoint for checking if compliacne requirements are paused for an Asset

feat: 🎸 check if compliance requirements are paused

---

src/claims/claims.controller.spec.ts
src/claims/claims.controller.ts
src/claims/claims.module.ts
src/claims/claims.service.spec.ts
src/claims/claims.service.ts
src/claims/dto/claim-target.dto.ts
src/claims/dto/modify-claims.dto.ts
src/corporate-actions/corporate-actions.controller.spec.ts
src/test-utils/consts.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts
src/transactions/transactions.util.ts

https://polymesh.atlassian.net/browse/DA-65
https://polymesh.atlassian.net/browse/DA-66
https://polymesh.atlassian.net/browse/DA-67
Adds methods to
- addClaims
- editClaims
- revokeClaims

feat: addClaims, editClaims, revokeClaims

---

src/portfolios/porfolios.controller.spec.ts
src/portfolios/portfolios.controller.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-75
get portfolio details for did

feat: 🎸 get portfolio details for did

---

src/settlements/settlements.controller.spec.ts
src/settlements/settlements.controller.ts
src/settlements/settlements.service.spec.ts
src/settlements/settlements.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-73 
- adds enpoint to reschedule a failed instruction changes/features.

 feat: 🎸 reschedule a failed instruction

---

src/portfolios/portfolios.service.ts

n/a
- Refactor to narrow findOne return type

refactor: 💡 use function overload to narrow find portfolio type

---

src/portfolios/dto/set-custodian.dto.ts
src/portfolios/porfolios.controller.spec.ts
src/portfolios/portfolios.controller.ts
src/portfolios/portfolios.service.spec.ts
src/portfolios/portfolios.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-77
- adds enpoint to set custodian for a portfolio

feat: 🎸 set portfolio custodian

---

README.md
src/signing/signing.controller.ts

n/a
also fixes typo in GET /signer/{signer}

docs: ✏️ add fireblocks envs to README file

---

package.json
src/portfolios/porfolios.controller.spec.ts
src/portfolios/portfolios.controller.ts
src/portfolios/portfolios.service.spec.ts
src/portfolios/portfolios.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts
yarn.lock

https://polymesh.atlassian.net/browse/DA-78
- adds endpoint to quit custody over portfolio

feat: 🎸 quit portfolio custody

---

src/identities/models/account-data.model.ts
src/portfolios/dto/get-transactions.dto.ts
src/portfolios/models/historic-settlement-leg.model.ts
src/portfolios/models/historic-settlement.model.ts
src/portfolios/models/settlement-leg.model.ts
src/portfolios/porfolios.controller.spec.ts
src/portfolios/portfolios.controller.ts
src/portfolios/portfolios.service.spec.ts
src/portfolios/portfolios.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-79
- adds endpoint to fetch the transaction history for a portfolio

feat: 🎸 get portfolio tx history

---

README.md
package.json
yarn.lock

Bump SDK version to v19 to support chain `5.2.0`

feat: 🎸 Bump SDK version to v19 for chain `5.2.0` support

---

src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/auth/strategies/api-key.strategy.ts
src/authorizations/authorizations.service.spec.ts
src/authorizations/authorizations.service.ts
src/common/errors.ts
src/common/filters/app-error-to-http-response.filter.spec.ts
src/common/filters/app-error-to-http-response.filter.ts
src/compliance/mocks/compliance-requirements.mock.ts
src/events/events.service.spec.ts
src/events/events.service.ts
src/notifications/notifications.service.spec.ts
src/notifications/notifications.service.ts
src/offerings/offerings.service.spec.ts
src/offerings/offerings.service.ts
src/polymesh/polymesh.service.ts
src/portfolios/porfolios.controller.spec.ts
src/signing/services/local-signing.service.spec.ts
src/signing/services/signing.service.ts
src/signing/services/vault-signing.service.spec.ts
src/subscriptions/subscriptions.service.spec.ts
src/subscriptions/subscriptions.service.ts
src/subsidy/subsidy.service.spec.ts
src/subsidy/subsidy.service.ts
src/transactions/transactions.util.spec.ts
src/transactions/transactions.util.ts

use AppError consistently in all services

refactor: 💡 standardize service errors

---

package.json
yarn.lock

Bump SDK to v19.2.0-alpha.3
NA

fix: 🐛 bump SDK to v19.2.0-alpha.3

---

.vscode/settings.json
src/accounts/accounts.controller.spec.ts
src/accounts/accounts.service.spec.ts
src/network/network.service.spec.ts
src/network/network.service.ts
src/test-utils/consts.ts
src/test-utils/mocks.ts
src/transactions/dto/transaction-hash-params.dto.ts
src/transactions/models/extrinsic-details.model.ts
src/transactions/transactions.consts.ts
src/transactions/transactions.controller.spec.ts
src/transactions/transactions.controller.ts
src/transactions/transactions.module.ts

DA-530
Add endpoint to get transaction details by hash

feat: 🎸 Add endpoint to get transaction details by hash

---

package.json
src/assets/assets.controller.spec.ts
src/assets/assets.service.spec.ts
src/assets/dto/create-asset.dto.ts
yarn.lock

DA-590
Removes the option to set investor uniqueness requirement for an asset. Also, bumps SDK to version `20.0.0`
BREAKING CHANGE: 🧨 `requireInvestorUniqueness` is removed from `CreateAssetDto`

feat: 🎸 Remove option to add investor uniqueness for an asset

---

package.json
yarn.lock

https://polymesh.atlassian.net/browse/DA-695
feat: 🎸 bump SDK to support Polymesh 5.4

feat: 🎸 bump SDK to support Polymesh 5.4

---

src/identities/identities.controller.spec.ts
src/identities/identities.controller.ts
src/identities/identities.service.spec.ts
src/identities/identities.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

DA-746
Add endpoint to get held Assets by a DID

feat: 🎸 Add endpoint to get held Assets by a DID

---

package.json
yarn.lock

N/A
Updates SDK to latest alpha to inlcude an asset.details fix on 5.4 chains

fix: 🐛 bump sdk version for 5.4 asset fix

---

package.json
yarn.lock

Add description in points. Use bulleting/numbering to list the changes/features.

feat: 🎸 upgrade sdk to 22.alpha-2

---

package.json
yarn.lock

N/A
include create custom asset types fix for v6.0

fix: 🐛 include latest sdk bug fix

---

package.json
yarn.lock

chore: 🤖 update sdk to 22.0.1

---

src/identities/identities.controller.spec.ts
src/identities/identities.controller.ts
src/settlements/models/grouped-instructions.model.ts
src/settlements/settlements.service.spec.ts
src/settlements/settlements.service.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-49
adds ednpoint to retrieve grouped insctuctions for identity

feat: 🎸 add endpoint to retrieve grouped instructions

---

src/claims/claims.controller.spec.ts
src/claims/claims.controller.ts
src/claims/claims.service.spec.ts
src/claims/claims.service.ts
src/claims/dto/claim.dto.spec.ts
src/claims/dto/claim.dto.ts
src/claims/dto/get-custom-claim-type.dto.ts
src/claims/dto/register-custom-claim-type.dto.ts
src/claims/models/custom-claim-type.model.ts
src/test-utils/mocks.ts

https://polymesh.atlassian.net/browse/DA-908
Allows registering and getting customClaimType and issuing CustomClaim

feat: register & get  CustomClaimType, allow CustomClaim

---

src/app.module.ts
src/assets/dto/create-asset.dto.ts
src/nfts/dto/collection-key.dto.ts
src/nfts/dto/create-nft-collection.dto.ts
src/nfts/dto/issue-nft.dto.ts
src/nfts/dto/metadata-value.dto.ts
src/nfts/dto/nft-params.dto.ts
src/nfts/dto/redeem-nft.dto.ts
src/nfts/models/collection-key.model.ts
src/nfts/models/nft-metadata-key.model.ts
src/nfts/models/nft-metadata.model.ts
src/nfts/models/nft.model.ts
src/nfts/nfts.controller.spec.ts
src/nfts/nfts.controller.ts
src/nfts/nfts.module.ts
src/nfts/nfts.service.spec.ts
src/nfts/nfts.service.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

✅ Closes: [DA-913](https://polymesh.atlassian.net/browse/DA-913)
add endpoint to allow management of NFT collections, including issuing, redeeming and fetching NFT details
[DA-913]: https://polymesh.atlassian.net/browse/DA-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 🎸 add NFT module

---

package.json
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/assets.util.ts
src/checkpoints/checkpoints.service.spec.ts
src/checkpoints/checkpoints.service.ts
src/common/decorators/transformation.ts
src/common/decorators/validation.ts
src/corporate-actions/corporate-actions.service.spec.ts
src/corporate-actions/corporate-actions.service.ts
src/nfts/nfts.service.spec.ts
src/nfts/nfts.service.ts
src/offerings/offerings.service.spec.ts
src/offerings/offerings.service.ts
src/portfolios/dto/portfolio-movement.dto.ts
src/portfolios/portfolios.service.ts
src/settlements/dto/leg-validation-params.dto.ts
src/settlements/dto/leg.dto.ts
src/settlements/models/leg.model.ts
src/settlements/settlements.controller.spec.ts
src/settlements/settlements.controller.ts
src/settlements/settlements.service.spec.ts
src/settlements/settlements.service.ts
src/settlements/settlements.util.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts
yarn.lock

✅ Closes: [DA-913](https://polymesh.atlassian.net/browse/DA-913)
Add NFT handling for common asset functionality, like adding documents. portfolios/move-assets and instructions/create now support `nfts` arg
BREAKING CHANGE: 🧨 InstructionModel leg "amount" is now optional. It will not be present when the leg is for an NFT
[DA-913]: https://polymesh.atlassian.net/browse/DA-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 🎸 support NFTs in /assets endpoints where appropriate

---

src/settlements/dto/leg-validation-params.dto.ts
src/settlements/settlements.service.spec.ts
src/settlements/settlements.service.ts

N/A
`alpha` had a failed test run due to a TS error around the leg-validations endpoint

test: 💍 fix leg-validations test

---

src/settlements/settlements.util.ts

fixes sonar smell + makes the comment more accurate

docs: ✏️ update TODO comment

---

README.md
src/common/dto/mortality-dto.ts
src/common/dto/transaction-options.dto.ts
src/signing/services/signing.service.ts
src/transactions/transactions.service.spec.ts
src/transactions/transactions.service.ts

[DA-955](https://polymesh.atlassian.net/browse/DA-955)
allow users to specify account nonce and transaction mortality
[DA-955]: https://polymesh.atlassian.net/browse/DA-955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 🎸 add nonce and mortality tx options

---

package.json
src/metadata/metadata.controller.spec.ts
src/metadata/metadata.controller.ts
src/metadata/metadata.service.spec.ts
src/metadata/metadata.service.ts
yarn.lock

DA-958
- Endpoint to clear value for an Asset Metadata
- Endpoint to remove a Local Asset Metadata
Also updates the SDK dependency to `23.0.0-alpha.37`

feat: 🎸 Adds new Asset Metadata endpoints

---

.github/CODEOWNERS
Jenkinsfile

Updates alpha with latest changes from master

Master into alpha

---

README.md
jest.config.js
package.json
src/app.module.ts
src/confidential-accounts/confidential-accounts.service.spec.ts
src/confidential-accounts/confidential-accounts.service.ts
src/confidential-transactions/models/confidential-affirmation.model.ts
src/identities/identities.controller.spec.ts
src/identities/identities.controller.ts
src/identities/identities.service.spec.ts
src/identities/identities.service.ts
src/middleware/confidential-assets-middleware/confidential-assets-middleware.controller.spec.ts
src/middleware/confidential-assets-middleware/confidential-assets-middleware.controller.ts
src/middleware/middleware.module.ts
src/polymesh/config/polymesh.config.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts
tsconfig.json
yarn.lock

DA-1110, DA-1070
Adds API to get held confidential assets, get involved confidential transactions

feat: 🎸 Add APIs using SQ SDK methods

---

package.json
src/accounts/accounts.controller.spec.ts
src/accounts/accounts.controller.ts
src/accounts/accounts.service.ts
src/accounts/models/multi-sig-details.model.ts
src/app.module.ts
src/multi-sigs/dto/create-multi-sig.dto.ts
src/multi-sigs/dto/join-creator.dto.ts
src/multi-sigs/dto/modify-multi-sig.dto.ts
src/multi-sigs/dto/multi-sig-params.dto.ts
src/multi-sigs/dto/multisig-proposal-params.dto.ts
src/multi-sigs/models/multi-sig-created.model.ts
src/multi-sigs/models/multi-sig-proposal-details.model.ts
src/multi-sigs/models/multi-sig-proposal.model.ts
src/multi-sigs/multi-sigs.controller.spec.ts
src/multi-sigs/multi-sigs.controller.ts
src/multi-sigs/multi-sigs.module.ts
src/multi-sigs/multi-sigs.service.spec.ts
src/multi-sigs/multi-sigs.service.ts
src/polymesh/polymesh.service.ts
src/test-utils/consts.ts
src/test-utils/mocks.ts
yarn.lock

[DA-1253](https://polymesh.atlassian.net/browse/DA-1253)
add endpoints to create and modify multiSigs, get proposal details and approve/reject them
[DA-1253]: https://polymesh.atlassian.net/browse/DA-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 🎸 add endpoints to manage multi sig accounts

---

src/network/mocks/middleware-metadata.mock.ts
src/network/mocks/network-properties.mock.ts
src/network/models/middleware-metadata.model.ts
src/network/models/network-properties.model.ts
src/network/network.controller.spec.ts
src/network/network.controller.ts
src/network/network.service.spec.ts
src/network/network.service.ts
src/test-utils/mocks.ts

https://polymesh.atlassian.net/browse/DA-1325
- adds genesis hash to network properties
- adds endpoint to fetch middleware metadata
-

feat: 🎸 get network and middleware metadata

---

src/multi-sigs/dto/create-multi-sig.dto.ts
src/multi-sigs/dto/set-multi-sig-admin.dto.ts
src/multi-sigs/multi-sigs.controller.spec.ts
src/multi-sigs/multi-sigs.controller.ts
src/multi-sigs/multi-sigs.service.spec.ts
src/multi-sigs/multi-sigs.service.ts

https://polymesh.atlassian.net/browse/DA-1304
- adds endpoint to get historical multi-sig proposals
- adds endpoint to get active multi-sig proposals
- adds enpoint to get multi-sig admin
- adds endpoint to get multi-sig payer
- adds endpoint to  set multi-sig admin
- adds endpoint to remove multi-sig payer
- adds endpoint to remove multi-sig admin

feat: 🎸 multiSig changes

---

package.json
src/assets/assets.controller.ts
src/assets/models/created-asset.model.ts
src/checkpoints/checkpoints.controller.ts
src/checkpoints/models/checkpoint-schedule.model.ts
src/common/decorators/validation.ts
src/common/models/extrinsic.model.ts
src/compliance/compliance-requirements.controller.ts
src/compliance/trusted-claim-issuers.controller.ts
src/corporate-actions/corporate-actions.controller.ts
src/corporate-actions/models/corporate-action.model.ts
src/identities/identities.controller.ts
src/identities/models/pre-approved.model.ts
src/metadata/models/metadata-entry.model.ts
src/nfts/nfts.controller.ts
src/settlements/dto/leg.dto.ts
src/test-utils/consts.ts
src/test-utils/mocks.ts
yarn.lock

DA-1347
https://polymesh.atlassian.net/browse/DA-1347
- return the assetId as `asset` in the response when creating an asset
-  use uuid format for asset ID

feat: 🎸 support asset IDs as uuids

---

src/assets/assets.controller.spec.ts
src/assets/assets.util.ts
src/assets/models/asset-balance.model.ts
src/assets/models/asset-details.model.ts

N/A
add assetId in GET /assets/{asset} response

feat: 🎸 add assetId in GET /assets/{asset} response

---

package.json
src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/assets.util.ts
src/assets/dto/link-ticker.dto.ts
src/assets/models/asset-details.model.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts
yarn.lock

DA-1368, DA-1370
- Return ticker value with asset details
- Add endpoints to link and unlink ticker from asset

feat: 🎸 Return ticker value with asset details and link/unlink ticker with asset

---

package.json

NA
Since we moved out of using semantic-release bot to update the package version, this got stuck at old version. Bumping to the next major version (assuming we will merge alpha into master pretty soon)

feat: 🎸 Bump package version

---

src/corporate-actions/corporate-actions.controller.spec.ts
src/corporate-actions/corporate-actions.controller.ts
src/corporate-actions/corporate-actions.service.spec.ts
src/corporate-actions/corporate-actions.service.ts
src/corporate-actions/models/distribution-payment.model.ts
src/test-utils/consts.ts

https://polymesh.atlassian.net/browse/DA-106
- adds an endpoint to get the payment history for A DividendDistribution

feat: 🎸 add endpoint to get paymentHistory for a distribution

---

src/assets/models/created-nft-collection.model.ts
src/nfts/dto/create-nft-collection.dto.ts
src/nfts/nfts.controller.ts

Return newly created nft collection when creating one

feat: 🎸 Return newly created nft collection when creating one

---

src/assets/assets.controller.spec.ts
src/assets/assets.util.ts
src/assets/models/asset-details.model.ts

https://polymesh.atlassian.net/browse/DA-96
- adjusts asset details endpoint to include fullAgents for an asset

feat: 🎸 enable fetching agents for an asset

---

package.json
src/developer-testing/developer-testing.service.spec.ts
src/developer-testing/developer-testing.service.ts
src/identities/identities.controller.spec.ts
src/identities/identities.controller.ts
yarn.lock

N/A
Remove an endpoint that has been marked for 2 years since the `testUtils` pallet is expected to be removed from the chain soon
BREAKING CHANGE: 🧨 POST /mock-cdd has been removed

feat: 🎸 remove POST /mock-cdd use /create-test-accounts instead

---

package.json
src/settlements/settlements.controller.spec.ts
src/settlements/settlements.controller.ts
src/settlements/venues.controller.spec.ts
src/settlements/venues.controller.ts
src/test-utils/mocks.ts
yarn.lock

Use `getLegsFromChain` for getting legs after creation

fix: 🐛 Use `getLegsFromChain` for getting legs after creation

---

src/assets/assets.controller.spec.ts
src/assets/assets.controller.ts
src/assets/assets.service.spec.ts
src/assets/assets.service.ts
src/assets/dto/create-permission-group.dto.ts
src/assets/models/created-custom-permission-group.model.ts
src/common/decorators/swagger.ts
src/common/decorators/validation.ts
src/test-utils/mocks.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-93
- adds endpoint to create a permission group for an asset

feat: 🎸 add endpoint to create permission group for asset

---

package.json
yarn.lock

This bumps SDK version to latest which will eventually fix approval/rejection/execution of instruction without waiting for middleware to process the instruction first.

feat: 🎸 Bump SDK version to v27.0.0-alpha.6

---

package.json
yarn.lock

Add description in points. Use bulleting/numbering to list the changes/features.

feat: 🎸 Bump SDK version to 27.0.0-alpha.9

---

src/permission-groups/permission-groups.controller.spec.ts
src/permission-groups/permission-groups.controller.ts
src/permission-groups/permission-groups.service.spec.ts
src/permission-groups/permission-groups.service.ts

https://polymesh.atlassian.net/browse/DA-99
- adds an endpoint to set the permissions for a permission group

feat: 🎸 modify permission group permissions

---

src/permission-groups/decorators/transformation.ts
src/permission-groups/decorators/validation.ts
src/permission-groups/dto/check-permissions.dto.ts
src/permission-groups/dto/group-permissions.dto.ts
src/permission-groups/dto/invite-agent-to-group.dto.ts
src/permission-groups/models/check-permissions-result.model.ts
src/permission-groups/permission-groups.controller.spec.ts
src/permission-groups/permission-groups.controller.ts
src/permission-groups/permission-groups.service.spec.ts
src/permission-groups/permission-groups.service.ts

https://polymesh.atlassian.net/browse/DA-100
- adds endpoint to check asset permissions for a did

feat: 🎸 check asset permissions for did

---

src/identities/identities.controller.spec.ts
src/identities/identities.controller.ts
src/identities/identities.service.spec.ts
src/identities/identities.service.ts
src/identities/models/asset-with-group.model.ts
src/test-utils/service-mocks.ts

https://polymesh.atlassian.net/browse/DA-97
- adds endpoint to fetch asset groups for which the did has permissions

feat: 🎸 get asset groups for did

---

package.json
yarn.lock

https://polymesh.atlassian.net/browse/DA-1208
updates sdk version to avoid infinite loop in getClaimScopes

fix: 🐛 update sdk version to avoid infinite loop

---

package.json
yarn.lock

N/A
Bump SDK version to 27.6.0

chore: 🤖 update SDK to 27.6.0

---

prepareRelease.sh

N/A
Should fix the swagger gen step blocking.

chore: 🤖 bump chain version used in swagger generation

---

package.json
yarn.lock

update the SDK to 27.7.0 to include moveFunds fix

fix: 🐛 portfolio move funds with ticker

---

src/checkpoints/dto/create-checkpoint-schedule.dto.ts

https://polymesh.atlassian.net/browse/DA-1206
fixes incorrect validation on create schedule dto

fix: 🐛 create schedule dto

---

src/checkpoints/checkpoints.controller.ts

- fixes route order in checkpoints controller -> placing Get('/:id') in bottom to avoid conflicts

fix: 🐛 route order in checkpoints controller

---

src/checkpoints/checkpoints.controller.ts

corrects the API response in swagger annotation

fix: 🐛 swagger annotation

---

src/common/decorators/transformation.ts
src/settlements/settlements.util.ts

https://polymesh.atlassian.net/browse/DA-1207
- fixes dryRun throwing an error if model uses FromEntity due to value.toHuman beeing not a function
- fixes endAfterBlock beeing incorrectly mapped to endBlock

fix: 🐛 dryRun and manualInstruction return

---

src/common/utils/functions.ts
src/network/dto/protocol-fees-query.dto.ts
src/network/models/protocol-fee.model.ts
src/network/network.controller.spec.ts
src/network/network.controller.ts
src/network/network.service.spec.ts
src/network/network.service.ts
src/test-utils/mocks.ts

https://polymesh.atlassian.net/browse/DA-1549
adds endpoint to get protocol fees

feat: 🎸 get protocol fees
