PolymeshAssociation/polymesh-rest-api

- .github/workflows/docker-image.yml
[DA-413](https://polymesh.atlassian.net/browse/DA-413)
migrate images to be published to the new polymesh association docker hub instead of the deprecated polymathnet one
> chore: 🤖 publish to association docker hub account

- package.json
- src/assets/assets.controller.spec.ts
- src/assets/assets.service.spec.ts
- src/assets/assets.service.ts
- src/assets/dto/redeem-tokens.dto.ts
- yarn.lock
DA-434
Provide option to redeem from a specific portfolio
BREAKING CHANGE: 🧨 `RedeemTokensDto` now contains `from` attribute to specify the portfolio from which tokens must be redeemed
> feat: 🎸 Option to redeem tokens from a specific portfolio

- src/settlements/dto/create-instruction.dto.ts
- src/settlements/models/instruction.model.ts
- src/settlements/settlements.util.ts
DA-435
- Allow optional `memo` field while creating instruction
- Also, returns the `memo` value in `InstructionModel`
> feat: 🎸 Allow optional `memo` field while creating instruction

- package.json
- src/accounts/accounts.controller.spec.ts
- src/accounts/accounts.controller.ts
- src/accounts/accounts.service.spec.ts
- src/accounts/accounts.service.ts
- src/accounts/accounts.util.spec.ts
- src/accounts/accounts.util.ts
- src/accounts/models/subsidy.model.ts
- src/test-utils/mocks.ts
- src/test-utils/service-mocks.ts
- yarn.lock
DA-6
Adds endpoint `/accounts/:account/subsidy` to fetch account subsidy
> feat: 🎸 Endpoint to get account subsidy

- src/assets/dto/create-asset.dto.ts
- src/settlements/dto/create-venue.dto.ts
N/A  
Default create asset to not require investor uniqueness. If enabled claims have to be made before settlements succeed, and it can be difficult to debug why they fail.
> docs: ✏️ use false investor uniqueness for create asset example

- .github/workflows/main.yml
- package.json
- release.config.js
- yarn.lock
https://polymesh.atlassian.net/browse/DA-438
The docker plugin failed to log in, which made me think if we really need it.
Currently we release by looking for a tag that starts with `v`, which the semantic release Github plugin should do. Also its using a personal access token, so it should trigger the existing job we have. (Apparently there is a default `$GITHUB_TOKEN` actions can use which won't trigger other actions when used)
> chore: 🤖 remove docker release plugin

- src/accounts/accounts.controller.spec.ts
- src/accounts/accounts.controller.ts
- src/accounts/accounts.service.spec.ts
- src/assets/assets.controller.spec.ts
- src/assets/assets.service.spec.ts
- src/auth/auth.controller.spec.ts
- src/auth/auth.service.spec.ts
- src/auth/repos/api-key.repo.suite.ts
- src/authorizations/authorizations.service.spec.ts
- src/checkpoints/checkpoints.controller.spec.ts
- src/checkpoints/checkpoints.service.spec.ts
- src/common/filters/app-error-to-http-response.filter.spec.ts
- src/corporate-actions/corporate-actions.controller.spec.ts
- src/corporate-actions/corporate-actions.service.spec.ts
- src/corporate-actions/dto/corporate-action-default-config.dto.spec.ts
- src/corporate-actions/dto/dividend-distribution.dto.spec.ts
- src/datastore/postgres/repos/api-key.repo.spec.ts
- src/datastore/postgres/repos/users.repo.spec.ts
- src/identities/dto/add-secondary-account-params.dto.spec.ts
- src/identities/identities.controller.spec.ts
- src/identities/identities.service.spec.ts
- src/portfolios/porfolios.controller.spec.ts
- src/portfolios/portfolios.service.spec.ts
- src/settlements/settlements.controller.spec.ts
- src/settlements/settlements.service.spec.ts
- src/test-utils/consts.ts
- src/users/users.controller.spec.ts
- src/users/users.service.spec.ts
Prep work for: [DA-375](https://polymesh.atlassian.net/browse/DA-375)
Refactors repeated '0x06'.padEnd calls into a `const`. Also separates signer and DID in some tests
> refactor: 💡 use const for signer in tests

- src/polymesh/polymesh.service.ts
N/A
Use mempool nonce when calling mock-cdd. 
Should allow for concurrent cdd creation and reduce the chance of getting the too low priority error.
> feat: 🎸 use mempool nonce when creating a mock-cdd claim

- jest.config.js
- src/accounts/accounts.service.spec.ts
- src/accounts/accounts.service.ts
- src/assets/assets.service.spec.ts
- src/assets/assets.service.ts
- src/assets/dto/ticker-params.dto.ts
- src/authorizations/authorizations.service.spec.ts
- src/authorizations/authorizations.service.ts
- src/checkpoints/checkpoints.service.spec.ts
- src/checkpoints/checkpoints.service.ts
- src/corporate-actions/corporate-actions.service.spec.ts
- src/corporate-actions/corporate-actions.service.ts
- src/identities/identities.controller.spec.ts
- src/identities/identities.service.spec.ts
- src/identities/identities.service.ts
- src/metadata/metadata.service.spec.ts
- src/metadata/metadata.service.ts
- src/offerings/offerings.service.spec.ts
- src/portfolios/portfolios.service.spec.ts
- src/portfolios/portfolios.service.ts
- src/settlements/settlements.service.spec.ts
- src/settlements/settlements.service.ts
- src/signing/signing.service.spec.ts
- src/subsidy/subsidy.service.spec.ts
- src/subsidy/subsidy.service.ts
- src/ticker-reservations/ticker-reservations.service.spec.ts
DA-468
Remove the repetitive handling of errors while fetching some storage values from SDK. Use generic `handleSdkError` to handle conversion of SDK errors to throw corresponding exceptions
> test: 💍 Use generic `handleSdkError` function to handle errors

- src/auth/repos/api-key.repo.suite.ts
- src/datastore/postgres/repos/api-key.repo.spec.ts
N/A
postgres api key test was failing async due to a error in the postgres mock. The spec did not fail due to not returning the expect
> test: 💍 fix api key test + mock implementation

- .github/workflows/docker-image.yml
this was introduced quite a while ago when we made releases manually: https://github.com/PolymeshAssociation/polymesh-rest-api/pull/42
The SDK doesn't use this filter and works like I would expect: https://github.com/PolymathNetwork/polymesh-sdk/blob/8ecfeac01e146a4b1dfa560488674011308aab69/.github/workflows/main.yml#L74
I was able to trigger the docker push of https://github.com/PolymeshAssociation/polymesh-rest-api/releases/tag/v2.5.0-alpha.1 by marking it as not a pre-release, so there is another potential solution there.
> chore: 🤖 publish all releases, not just "published" ones

- .github/workflows/docker-image.yml
Reverts PolymeshAssociation/polymesh-rest-api#164
It seems like this didn't work, and made it so unmarking the release didn't trigger the pipeline.
I think unchecking the box for alpha isn't too bad, so I think this reversion will be OK for now.
> Revert "chore: 🤖 publish all releases, not just "published" ones"

- README.md
- src/polymesh/config/polymesh.config.ts
- src/portfolios/porfolios.controller.spec.ts
- src/portfolios/portfolios.controller.ts
- src/portfolios/portfolios.service.spec.ts
- src/portfolios/portfolios.service.ts
- src/test-utils/mocks.ts
- src/test-utils/service-mocks.ts
DA-80
* Adds endpoint `GET /identities/:did/portfolios/:id/created-at` to get event details when the specified portfolio was created
* Add support for middleware V2
> feat: 🎸 Add endpoint to get Portfolio creation event details and Middleware V2 support

- src/auth/auth.utils.ts
- src/main.ts
DA-445
This allows swagger to enable apiKey authorization if `AUTH_STRATEGY` is set as `apiKey`
> feat: 🎸 Add API Key Swagger support

- src/common/decorators/transformation.ts
NA
Date type attributes weren't correctly transformed to ISO string when the corresponding model was as part of result set or paginated data.
> fix: 🐛 Correct parsing of date attributes for paginated data

- commitlint.config.js
DA-501
While creating the commit with changes in package.json, src/main.ts with version updates, the commit message was too long and failed in commitlint step as shown [here](https://github.com/PolymeshAssociation/polymesh-rest-api/actions/runs/4384800680). 
This PR excludes such commits from commitlint
> fix: 🐛 Ignore release commit from commitlint

- commitlint.config.js
DA-501
Fixes the commitlint regex to work with long prereleases commit names such as `chore(release): 2.5.0-alpha.3.15 [skip ci]`
> fix: 🐛 Update commitlint ignore regex to suppport prereleases

- .github/workflows/main.yml
- Dockerfile
- src/accounts/accounts.service.ts
- src/assets/assets.service.ts
- src/authorizations/authorizations.service.ts
- src/checkpoints/checkpoints.service.ts
- src/common/errors.ts
- src/corporate-actions/corporate-actions.service.ts
- src/identities/identities.service.ts
- src/main.ts
- src/metadata/metadata.service.ts
- src/portfolios/portfolios.service.ts
- src/settlements/settlements.service.ts
- src/subsidy/subsidy.service.ts
- src/transactions/transactions.service.ts
- src/transactions/transactions.util.spec.ts
- src/transactions/transactions.util.ts
makes handleSdkError return an error and have the caller throw to provide more flexibility. Adds in global unhandledPromiseRejection handler to ensure compatibility with V18
✅ Closes: [DA-546](https://polymesh.atlassian.net/browse/DA-546)
[DA-546]: https://polymesh.atlassian.net/browse/DA-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: 🤖 upgrade to node V18 runtime

- src/portfolios/portfolios.service.spec.ts
- src/portfolios/portfolios.service.ts
N/A
Fix findOne when portfolio ID 0 is given
> fix: 🐛 finding default portfolio when id 0 is given

- chain-entry.sh
- docker-compose.yml
- prepareRelease.sh
- src/main.ts
N/A
generate swagger was failing due to testnet being on 5.x. This change modifes the prepareRelease.sh script to start up a docker image to use instead
e.g: https://github.com/PolymeshAssociation/polymesh-rest-api/actions/runs/5726853573/job/15521667477
> chore: 🤖 remove external chain dep for build

- package.json
- src/accounts/accounts.controller.spec.ts
- src/accounts/accounts.service.spec.ts
- src/accounts/accounts.service.ts
- src/accounts/dto/transaction-history-filters.dto.ts
- src/portfolios/porfolios.controller.spec.ts
- src/portfolios/portfolios.controller.ts
- src/portfolios/portfolios.service.ts
- src/test-utils/mocks.ts
- yarn.lock
updates to latest dual-sdk
BREAKING CHANGE: 🧨 TransactionHistoryFilersDto removes `order` and `field` params, replaced by `orderBy` field. Affects `GET /accounts/{account}/transactions`
> feat: 🎸 update to sdk v22-beta.1

- src/transactions/transactions.util.spec.ts
- src/transactions/transactions.util.ts
✅ Closes: [DA-932](https://polymesh.atlassian.net/browse/DA-932)
use method.length to check if args should be given or not in `prepareProcedure`
[DA-932]: https://polymesh.atlassian.net/browse/DA-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: 🐛 error when optional arg methods given no args

- package.json
- src/confidential-accounts/confidential-accounts.controller.spec.ts
- src/confidential-accounts/confidential-accounts.controller.ts
- src/confidential-accounts/confidential-accounts.service.spec.ts
- src/confidential-accounts/confidential-accounts.service.ts
- src/confidential-accounts/models/confidential-asset-balance.model.ts
- src/confidential-assets/confidential-assets.controller.spec.ts
- src/confidential-assets/confidential-assets.controller.ts
- src/confidential-assets/confidential-assets.module.ts
- src/confidential-assets/confidential-assets.service.spec.ts
- src/confidential-assets/confidential-assets.service.ts
- src/confidential-assets/confidential-assets.util.ts
- src/confidential-assets/dto/burn-confidential-assets.dto.ts
- src/confidential-assets/dto/confidential-asset-id-params.dto.ts
- src/confidential-assets/dto/toggle-freeze-confidential-account-asset.dto.ts
- src/confidential-assets/models/confidential-asset-details.model.ts
- src/confidential-proofs/confidential-proofs.controller.spec.ts
- src/confidential-proofs/confidential-proofs.controller.ts
- src/confidential-proofs/confidential-proofs.module.ts
- src/confidential-proofs/confidential-proofs.service.spec.ts
- src/confidential-proofs/confidential-proofs.service.ts
- src/confidential-transactions/confidential-transactions.controller.spec.ts
- src/confidential-transactions/confidential-transactions.controller.ts
- src/confidential-transactions/confidential-transactions.service.spec.ts
- src/confidential-transactions/confidential-transactions.service.ts
- yarn.lock
DA-1091, DA-1092, DA-1093, DA-1113, DA-1114, DA-1094, DA-1115
Adds API to - 
* freeze/unfreeze a confidential asset
* freeze/unfreeze a confidential account 
* get all balances and incoming balances
* get specific confidential asset balance / incoming balance
* get whether a confidential account has been frozen for a specific confidential asset id
* get details whether a confidential asset is frozen
* burn confidential asset
* get pending affirmations count
> feat: 🎸 Add APIs to freeze/unfreeze confidential asset/account

- src/app.module.ts
- src/confidential-assets/confidential-assets.service.spec.ts
- src/confidential-assets/confidential-assets.service.ts
- src/middleware/confidential-assets-middleware/confidential-assets-middleware.controller.spec.ts
- src/middleware/confidential-assets-middleware/confidential-assets-middleware.controller.ts
- src/middleware/middleware.module.ts
DA-1108
Adds API to get creation event details for a confidential asset
> feat: 🎸 Add API to get creation event data for CA

- src/claims/decorators/get-custom-claim-type.pipe.ts
- src/confidential-assets/confidential-assets.service.spec.ts
- src/confidential-assets/confidential-assets.service.ts
- src/confidential-assets/models/confidential-asset-transaction.model.ts
- src/middleware/confidential-assets-middleware/confidential-assets-middleware.controller.spec.ts
- src/middleware/confidential-assets-middleware/confidential-assets-middleware.controller.ts
[DA-1109](https://polymesh.atlassian.net/browse/DA-1109)
add GET /confidential-assets/{confidentialAssetId}/transactions to allow fetching of transaction involving the asset
[DA-1109]: https://polymesh.atlassian.net/browse/DA-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add asset tranaction history end point

- src/identities/dto/register-identity.dto.ts
`createCdd` would always be false, even when specified in the request. Adds a decorator to DTO param so `createCdd` is parsed properly
> fix: 🐛 cdd not created with /identities/register

- src/settlements/settlements.controller.spec.ts
- src/settlements/settlements.controller.ts
- src/settlements/settlements.service.spec.ts
- src/settlements/settlements.service.ts
- src/test-utils/mocks.ts
https://polymesh.atlassian.net/browse/DA-1302
- makes the venueId optional in settlements service
- adds a new endpoint under settlements controller to create an instruction withouth venueId
> feat: 🎸 make venueId optional for createInstruction

- package.json
- src/claims/dto/claim.dto.spec.ts
- src/claims/dto/claim.dto.ts
- yarn.lock
https://polymesh.atlassian.net/browse/DA-1208
- updates sdk to 26.2.0-alpha.1
- update logic to allow for CustomClaim to be without scope defined
- uses latest SDK to allow to retrieve CustomClaim scopes for did if middleware is enabled
> feat: 🎸 support customClaim withouth scope

- src/corporate-actions/corporate-actions.controller.spec.ts
- src/identities/identities.controller.spec.ts
- src/identities/identities.controller.ts
- src/identities/identities.service.spec.ts
- src/identities/identities.service.ts
- src/test-utils/mocks.ts
- src/test-utils/service-mocks.ts
https://polymesh.atlassian.net/browse/DA-105
- adds an endpoint to retireve all eligible dividend distributions for an Identity
> feat: 🎸 get all eligible dividend distributions for did

- src/accounts/models/asset-permissions.model.ts
- src/assets/dto/create-asset.dto.ts
- src/claims/decorators/validation.ts
- src/common/decorators/validation.ts
- src/compliance/dto/condition.dto.ts
- src/compliance/dto/set-requirements.dto.ts
- src/identities/dto/asset-permissions.dto.ts
- src/nfts/dto/create-nft-collection.dto.ts
- src/portfolios/dto/portfolio-movement.dto.ts
- src/settlements/dto/create-venue.dto.ts
- src/settlements/dto/leg-validation-params.dto.ts
DA-1399
-  Add missing `IsOptional` to `CreateVenueDto.signers`. Without the `IsOptional` annotation, creating a venue without signers was not posssible. Adding it, allows the functionality to work as expected
- Fix validations for `ScopeType.Asset` in `ScopeDto` . `ScopeDto` was allowing all values of asset ID to pass when `type` was set to `ScopeType.Asset`. This adds in check for it to be a valid Asset ID
- Update swagger examples to display asset IDs
- Add missing `IsOptional` to `securityIdentifiers` in `CreateAssetDto` and `CreateNftCollectionDto`
> Fix validations

- package.json
- src/assets/assets.service.spec.ts
- src/nfts/models/nft.model.ts
- src/nfts/nfts.service.spec.ts
- src/nfts/nfts.service.ts
While getting nft collection from SDK, REST API service was always expecting ticker to be passed. This PR fixes the logic there. 
BREAKING CHANGE: 🧨 `ticker` field in `NftModel` has been renamed to `collection`
> fix: 🐛 Add missing support for NFT collection in UUID format

- docker-compose.yml
- src/metadata/metadata.controller.ts
- src/signing/dto/add-local-signer.dto.ts
- src/signing/services/local-signing.service.spec.ts
- src/signing/services/local-signing.service.ts
- src/signing/services/signing.service.ts
- src/signing/services/vault-signing.service.spec.ts
- src/signing/signing.controller.spec.ts
- src/signing/signing.controller.ts
[DA-1462](https://polymesh.atlassian.net/browse/DA-1462)
add POST /signer when using a local signing manager to dynamically add keys
[DA-1462]: https://polymesh.atlassian.net/browse/DA-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: 🎸 add local signing key endpoint

- .github/workflows/docker-image.yml
- Dockerfile
- Run corepack enable before dropping privileges so Yarn can create its shims without hitting permission errors.
- Keep the build stages running as the node user once that setup is complete.
- Set YARN_ENABLE_SCRIPTS=false to replace the old --ignore-scripts flag removed in Yarn 4.
- Switch yarn install to use Yarn 4–compatible flags (--immutable, --inline-builds, --mode=skip-build)
> fix: 🐛 corepack permission issues
